import os


PATH = os.path.dirname(os.path.abspath(__file__))

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "COVID Warrior"

ENEMY_SCALING_PLAYER = 0.5
ENEMY_SCALING_COIN = 0.2
ENEMY_COUNT = 12

SPRITE_SCALING_PLAYER = 0.5
SPRITE_SCALING_ENEMY = 0.1
SPRITE_SCALING_PROJECTILE = 0.7
BULLET_SPEED = 6

PLAYER_VELOCITY = 7

KILL_COUNT = 0

LEVEL = 1
ENEMY_VELOCITY = 0.5